# 此工作流程使用未经 GitHub 认证的操作。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档的约束。

name: tfsec
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tfsec:
    name: 运行 tfsec sarif 报告
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: 加固运行器（审计所有出站调用）
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - name: 检出代码
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 运行 tfsec
        uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608
        with:
          sarif_file: tfsec.sarif

      - name: 上传 SARIF 文件
        uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
        with:
          sarif_file: tfsec.sarif
